name: macOS Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Premake
      uses: checkraisefold/setup-premake@v2.0
      with:
        version: 5.0.0-alpha16
        
    - name: Run Premake
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        premake5 gmake2
        
    - name: Build binaries
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        make config=release_mac64
        make config=debug_mac64
        
    - name: Upload release
      uses: actions/upload-artifact@v2.2.4
      with:
        name: ROBLOXLink.dylib
        path: bin/Release/libROBLOXLink.dylib
        
    - name: Upload debug
      uses: actions/upload-artifact@v2.2.4
      with:
        name: debug_ROBLOXLink.dylibd
        path: bin/Debug/libROBLOXLink.dylib
